// JavaScript Document

function count() {
	document.write('<table cellpadding="0" cellspacing="0" border="0" width="88" height="31" style="line-height:0;width:88px;">	<tr style="height:10px;">	<td style="padding:0;width:38px;height:10px;">	<a href="http://www.24log.de" target="_blank"><img src="http://counter.24log.ru/buttons/24/bg24-12_1.gif" width="38" height="10" border="0" alt="Besucherzahler" title="Besucherzahler " style="margin:0;padding:0;" /></a>	</td>	<td style="padding:0;width:50px;height:10px;">	<a href="http://www.russianwoman.ca" target="_blank"><img src="http://counter.24log.ru/buttons/24/bg24-12_3.gif" width="50" height="10" border="0" alt="mail order brides" style="margin:0;padding:0;"></a>	</td>	</tr>	<tr style="height:21px;">	<td style="padding:0;width:38px;height:21px">	<a href="http://www.24log.ru" target="_blank"><img src="http://counter.24log.ru/buttons/24/bg24-12_2.gif" width="38" height="21" alt="счетчик посещений" title="счетчик посещений" border="0" style="margin:0;padding:0;" /></a>	</td>	<script type="text/javascript" language="javascript">count_p()</script>	</tr>	</table>	<NOSCRIPT><a href="http://www.1russianbrides.com">how to marry a russian woman</a></NOSCRIPT>');}

function count_p(){
document.write('<td style="padding:0px;width:50px;height:21px;"><a href="http://www.24log.ru/rating/rating.php?c=15" target="_blank"><img border="0" width="50" height="21" src="http://counter.24log.ru/counter?id=154938&t=24&st=12&r='+escape(document.referrer)+'&u='+escape(document.URL)+'&s='+((typeof(screen)=='undefined')?'':screen.width+'x'+screen.height+'x'+(screen.colorDepth?screen.colorDepth:screen.pixelDepth))+'&rnd='+Math.random()+'" alt="Рейтинг: Учеба" title="Показано число просмотров всего и за сегодня" style="margin:0;padding:0;" /></a></td>');}

function clock(){
	document.write('	<script type="text/javascript" src="http://www.24webclock.com/clock24.js"></script>	<table border="0" bgcolor="#a0a0a0" cellspacing=1 cellpadding=3 class="clock24st" style="line-height:14px; padding:0;">	<tr>	<td bgcolor="#FFFFFF" class="clock24std" style="font-family:arial; font-size:12px;">	<a href="http://www.24webclock.com/"><img src="http://www.24webclock.com/ico.gif" width="14" height="14" border="0" alt="Clock for website" align="left" hspace="2"></a><a href="http://www.24webclock.com/ru/" style="text-decoration:none;">	<span class="clock24s" id="clock24_73246" style="color:#6393C3;">часы для сайта html</span></a>	</td>	</tr>	</table>	<script type="text/javascript">	var clock24_73246 = new clock24("73246",360,"%dd / %M / %yyyy %W %hh:%nn:%ss","ru");clock24_73246.daylight("KZ"); clock24_73246.refresh();	</script>	');}
//
function build(){
	document.write('<table border="0" cellspacing="5" cellpadding="0"><tr><td><script type="text/javascript" language="javascript">count()</script></td><td valign="bottom"><script type="text/javascript" language="javascript">clock()</script></td></tr></table>');}
